# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3284bd97743bfb80a327ebc8cff2fdc83a7fceb645519aef73a4d510626e8b6976e1c20ce23ac996737cb43123abc351b217f73396f555ccf3cb5fd2c85a326

test:
  secret_key_base: 35e0913fb9712f68ef81f9b34d574158e90af99d8e8ba8befce89d132eaab218256385f3f9ede1a97f148bf68fbd83e437921125afb399ddacc3158815eec1cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
